core:
    pattern:  /
    defaults: { _controller: 'FabrCoreBundle:Default:view' }

core_login:
    pattern:  /login
    defaults: { _controller: 'FabrCoreBundle:Security:login' }

core_login_check:
    pattern:  /login/check

core_logout:
    pattern:  /logout

core_department_view:
    pattern:  /users/{path}
    defaults:
        _controller: 'FabrCoreBundle:Department:view'
        path: ''
    requirements:
        path: .*