security:
    encoders:
        Fabr\CoreBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: FabrCoreBundle:User, property: email }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                check_path: /login/check
                login_path: /login
            logout: true
            security: true
            anonymous: true

    access_control:
        - { path: ^/admin, role: ROLE_ADMIN, ip: 127.0.0.1 }
        - { path: ^/,      role: IS_AUTHENTICATED_ANONYMOUSLY }